# Site settings
title: Alex&#178;a
description: > # this means to ignore newlines until "baseurl:"
  A blogger that makes Unity tutorials, talks about game journalism and so on...
url: "http://alexxacol.cf" # the base hostname & protocol for your site
baseurl: /blog # the subpath of your site, e.g. /blog/
twitter_username: AlexxaCol
github_username:  AlexxaCol

# Build settings
markdown: kramdown
